version: '3'
services:
  wildbeast:
    image: DeviLShAnto/DeviL-Bot
    env_file:
      - .env
    links:
    - arango
    - lavalink
    depends_on:
      - arango
      - lavalink
      - install
  arango:
    image: arangodb:3.3.10
    env_file:
      - arangodb.env
  install:
    restart: 'no'
    links:
      - arango
    environment:
      ARANGO_URI: http://arango:8529
    image: DeviLShAnto/DeviL-Bot
    depends_on:
      - arango
    command: npm run-script dbcreate
  lavalink:
    image: fredboat/lavalink:v2
    env_file:
      - lavalink.env
